language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-9.0.1.0
services:
  - mongodb
  - redis
addons:
  code_climate:
    repo_token: e3e4fc5da17ef3e332a5f62ce5a12d727ad472f367e41278df9d951b912cc748
  apt:
    packages:
      - libzmq3-dev
notifications:
  irc:
    channels: "chat.freenode.net#carbonmu"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
