language: ruby
cache: bundler
sudo: false
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - jruby-9.0.1.0
services:
  - mongodb
  - redis
addons:
  apt:
    packages:
      - libzmq3-dev
notifications:
  irc:
    channels: "chat.freenode.net#carbonmu"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
